package com.cavetale.mirage;

public enum EntityFlag {
    ENTITY_ON_FIRE(0x01),
    ENTITY_CROUCHING(0x02),
    ENTITY_UNUSED_RIDING(0x04),
    ENTITY_SPRINTING(0x08),
    ENTITY_SWIMMING(0x10),
    ENTITY_INVISIBLE(0x20),
    ENTITY_GLOWING(0x40),
    ENTITY_FLYING_ELYTRA(0x80),
    ARROW_CRIT(0x01),
    LIVING_HAND_ACTIVE(0x01),
    LIVING_OFF_HAND(0x02),
    PLAYER_SKIN_CAPE(0x01),
    PLAYER_SKIN_JACKET(0x02),
    PLAYER_SKIN_LEFT_SLEEVE(0x04),
    PLAYER_SKIN_RIGHT_SLEEVE(0x08),
    PLAYER_SKIN_LEFT_PANTS(0x10),
    PLAYER_SKIN_RIGHT_PANTS(0x20),
    PLAYER_SKIN_HAT(0x40),
    PLAYER_SKIN_UNUSED(0x80),
    PLAYER_SKIN_ALL(0x7e),
    ARMOR_STAND_SMALL(0x01),
    ARMOR_STAND_ARMS(0x04),
    ARMOR_STAND_NO_BASEPLATE(0x08),
    ARMOR_STAND_MARKER(0x10),
    INSENTIENT_NO_AI(0x01),
    INSENTIENT_LEFT_HANDED(0x02),
    BAT_HANGING(0x01),
    ABSTRACT_HORSE_UNUSED(0x01),
    ABSTRACT_HORSE_TAME(0x02),
    ABSTRACT_HORSE_SADDLED(0x04),
    ABSTRACT_HORSE_BRED(0x08),
    ABSTRACT_HORSE_EATING(0x10),
    ABSTRACT_HORSE_REARING(0x20),
    ABSTRACT_HORSE_MOUTH_OPEN(0x40),
    ABSTRACT_HORSE_UNUSED2(0x80),
    SHEEP_COLOR_MASK(0x0F),
    SHEEP_SHEARED(0x10),
    TAMEABLE_SITTING(0x01),
    TAMEABLE_ANGRY(0x02),
    TAMEABLE_TAMED(0x04),
    IRON_GOLEM_PLAYER_CREATED(0x01),
    SNOWMAN_HAS_PUMPKIN_HAT(0x10),
    BLAZE_ON_FIRE(0x01),
    ABSTRACT_ILLAGER_HAS_TARGET(0x01),
    VEX_ATTACK_MODE(0x01),
    SPIDER_CLIMBING(0x01);

    public final int bitMask;

    EntityFlag(int bitMask) {
        this.bitMask = bitMask;
    }
}
